from __future__ import annotations

import re
from typing import Any, Iterator

# Button payloads must match the format generated by WhatsAppClient.
_BUTTON_PATTERN = re.compile(r"(approve|reject)_(AGR-[A-Z0-9]{1,96})")

# Accept explicit text decisions only; ambiguous phrases are excluded.
_TEXT_PATTERN = re.compile(
    r"(approve|approved|reject|rejected)" r"(?:\s+(AGR-[A-Z0-9]{1,96}))?",
    re.IGNORECASE,
)


def _objects(value: Any) -> Iterator[dict[str, Any]]:
    # Ignore malformed list members without discarding valid batch entries.
    if isinstance(value, list):
        for item in value:
            if isinstance(item, dict):
                yield item


def _identifier(value: Any, maximum: int = 512) -> str | None:
    if not isinstance(value, str):
        return None

    if not value or len(value) > maximum or value != value.strip():
        return None

    return value


def _message_content(
    message: dict[str, Any],
) -> tuple[str, bool] | None:
    # Return the original content and whether it represents a button payload.
    kind = message.get("type")

    if kind == "button":
        button = message.get("button")

        if isinstance(button, dict):
            content = button.get("payload")
        else:
            return None

        is_button = True

    elif kind == "interactive":
        interactive = message.get("interactive")

        if (
            not isinstance(interactive, dict)
            or interactive.get("type") != "button_reply"
        ):
            return None

        reply = interactive.get("button_reply")

        if not isinstance(reply, dict):
            return None

        content = reply.get("id")
        is_button = True

    elif kind == "text":
        text = message.get("text")

        if not isinstance(text, dict):
            return None

        content = text.get("body")
        is_button = False

    else:
        return None

    if not isinstance(content, str) or not content.strip():
        return None

    if len(content) > 4096:
        return None

    return content, is_button


def extract_responses(
    payload: Any,
    *,
    expected_phone_number_id: str,
) -> Iterator[dict[str, Any]]:
    # Account routing is checked separately from webhook signature verification.
    if (
        not isinstance(expected_phone_number_id, str)
        or re.fullmatch(r"[0-9]+", expected_phone_number_id) is None
    ):
        raise ValueError("A valid expected_phone_number_id is required.")

    if (
        not isinstance(payload, dict)
        or payload.get("object") != "whatsapp_business_account"
    ):
        return

    for entry in _objects(payload.get("entry")):
        for change in _objects(entry.get("changes")):
            if change.get("field") != "messages":
                continue

            value = change.get("value")

            if not isinstance(value, dict):
                continue

            metadata = value.get("metadata")

            if (
                not isinstance(metadata, dict)
                or metadata.get("phone_number_id") != expected_phone_number_id
            ):
                continue

            for message in _objects(value.get("messages")):
                message_id = _identifier(message.get("id"))
                phone = message.get("from")

                # Preserve the sender supplied by Meta without coercing values.
                if (
                    message_id is None
                    or not isinstance(phone, str)
                    or re.fullmatch(r"[1-9][0-9]{0,14}", phone) is None
                ):
                    continue

                context = message.get("context")
                context_id = None

                if context is not None:
                    if not isinstance(context, dict):
                        continue

                    context_id = _identifier(context.get("id"))

                    if context_id is None:
                        continue

                content = _message_content(message)

                if content is None:
                    continue

                original_text, is_button = content

                if is_button:
                    match = _BUTTON_PATTERN.fullmatch(original_text)
                else:
                    match = _TEXT_PATTERN.fullmatch(original_text.strip())

                if match is None:
                    continue

                command = match.group(1).lower()
                reference = match.group(2)

                if reference is not None:
                    reference = reference.upper()

                # A decision must identify a task directly or through reply context.
                if reference is None and context_id is None:
                    continue

                yield {
                    "action": (
                        "rejected"
                        if command in {"reject", "rejected"}
                        else "approved"
                    ),
                    "reference": reference,
                    "context_id": context_id,
                    "phone": phone,
                    "message_id": message_id,
                    "text": original_text,
                }
